name: Deploy to Hugging Face Space

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Configure git and push to HF Space
        env:
          HF_TOKEN: ${{ secrets.RESUME_LLM }}
        run: |
          git config --global user.email "arthur830119@gmail.com"
          git config --global user.name "ArthurLin"
          git remote add hf https://user:${HF_TOKEN}@huggingface.co/spaces/ArthurLin/resume_recommendation_LLM
          git push hf master --force
