name: Deploy to Hugging Face Space

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install huggingface_hub
        run: pip install huggingface_hub

      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.RESUME_LLM }}
        run: huggingface-cli login --token $HF_TOKEN

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.RESUME_LLM }}
        run: |
          git config --global user.email "arthur830119@gmail.com"
          git config --global user.name "ArthurLin"
          git remote add hf https://huggingface.co/spaces/ArthurLin/resume_recommendation_LLM
          git push hf main --force
